pipeline:
  install:
    image: node:10
    commands:
      - npm install
  test:
    image: node:10
    commands:
      - npm test
  build:
    image: node:10
    commands:
      - npm run build
    when:
      event: tag
  deploy:
    image: node:10
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_DEPLOY_TOKEN}" > ~/.npmrc
      - echo "unsafe-perm=true" >> ~/.npmrc
      - npm publish
    secrets:
      - npm_deploy_token
    when:
      event: tag
      branch:
        - include: [ v* ]